name: Generate GitHub Summary Cards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: bikram73
          AUTO_PUSH: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push cards to summary-cards branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: summary-cards
          build_dir: profile-summary-card-output
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
